<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../environment.props" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <!-- Match the installed Harmony/MonoMod Cecil ABI. No publicized game references. -->
    <Reference Include="Mono.Cecil" HintPath="$(BepInExPath)/core/Mono.Cecil.dll" />
    <Reference Include="MonoMod.Utils" HintPath="$(BepInExPath)/core/MonoMod.Utils.dll" Private="false" />
    <Reference Include="0Harmony" HintPath="$(BepInExPath)/core/0Harmony.dll" Private="false" />
    <Reference Include="assembly_valheim" HintPath="$(CorlibPath)/assembly_valheim.dll" Private="false" />
    <Reference Include="assembly_utils" HintPath="$(CorlibPath)/assembly_utils.dll" Private="false" />
    <Reference Include="UnityEngine.CoreModule" HintPath="$(CorlibPath)/UnityEngine.CoreModule.dll" Private="false" />
  </ItemGroup>
</Project>
